### ISSUE TITLE
Hide IDs in Land Use 

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-britain#157]
Don't show the Land Use Category IDs in the Current Land Use dropdown in the Land Use Category (shown in brackets in the screenshot below)

![image](https://github.com/colouring-cities/colouring-core/assets/21125422/08d056b5-9632-4567-8cba-265ef61179d9)

**Comment by polly64** [comment]
@mdsimpson42 is this done and ready to close?

**Comment by mdsimpson42** [comment]
No, I've looked a few times, but I can't find a way to get rid of the IDs. The best I managed was to hide the IDs but the empty brackets were still there - and I'm concerned that the IDs might be used for something.

Can you remember who developed this initially?

**Comment by mdsimpson42** [comment]
Found a pull request discussing this issue:
https://github.com/colouring-cities/colouring-core/pull/785

There was some discussion about whether to remove the IDs or not. If we're sure we want to go ahead with it, I know how to do it now (and I'll close that pull request too).

**Comment by polly64** [comment]
@mdsimpson42 yes I think we should remove IDs

**Comment by mdsimpson42** [comment]
This is now done. It has been merged to main and deployed to Staging and will percolate through to Production at some point, if it hasn't already.
