### ISSUE TITLE
Require source, create undo button and other smaller tasks

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#165]
@mdsimpson42 @matkoniecz 
Many below also for colouring cities core but want to now make Colouring Core  issues just ones we want to co-work with international engineering team on. I still would like to work experimentally with  Colouring Britain and integrate new code into core respository even though we can't think of it as the prototype as other countries will also be beginning to contribute/co-work on code soon.

- [x] Create new Github repository - Colouring Britain and change name Colouring London to Colouring Britain as we can now access London and loughborough on same weblink
- [x] Facilitate loughborough post codes
- [x] ~~Change text with PH on landing page~~ (existing issue, see below)
- [x] colouring-cities/colouring-core#1369
- [x] colouring-cities/colouring-britain#188
- [x] Need to change Architectural style to Architectural Style/Historical Period - also for colouring core
- [x] ~~How can we best enable moderated boxes for architects' names?~~ (existing issue, see below)
- [x] Source link opens in land use under specific when no link required e.g for professional knoweldge 
- [x] Architectural style needs autofil for all copy boxes like others

**EDIT: I want to avoid making this kind of issue in the future, not only is it full of duplicates, but there are lots of separate, unrelated issues here. Task lists like this should only be used for similar, related issues - i.e. minor interface tweaks to one category. Separate issues for each feature are prefered.**

**Comment by mdsimpson42** [comment]
Landing Page Text Issue #1291

**Comment by mdsimpson42** [comment]
@matkoniecz @polly64 Is there a separate issue for Loughborough Postcodes/has this been implemented yet?

**Comment by mdsimpson42** [comment]
Moderating text boxes issue https://github.com/colouring-cities/colouring-britain/issues/192

**Comment by mdsimpson42** [comment]
More info needed on the last point. Might be better to create as a separate issue?

**Comment by mdsimpson42** [comment]
I'm closing this issue as everything in it has either been completed, or is addressed in a separate issue.
