### ISSUE TITLE
migrate to new domain that refers to Britain, not London

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-britain#171]
as discussed with @polly64

**Comment by matkoniecz** [comment]
Assigning @polly64 as next task is finding/obtaining domain.

**Comment by polly64** [comment]
@matkoniecz we have colouringbritain.org paid til 2026. What are options for adding cities/towns to this e.g colouringbritain_Loughborough?

**Comment by polly64** [comment]
Colouring London is part Colouring Cities.  The Colouring Cities Research Programme (CCRP), led by the Alan Turing Institute, is [an international consortium of academic institutions](https://github.com/colouring-cities/colouring-cities.github.io) involved in building research. Our aim is to maximise accessibility to building-level data across countries, to help improve stock quality, efficiency, sustainability and resilience and meet net-zero goals.

New data and features are added all the time. We are keen to engage as many people as possible in platform development. Whether you are a resident, or a stakeholder in academia, government, industry or the third sector, any help you can give colouring in our Colouring Cities maps, and enriching and verifying our open databases with your knowledge, is greatly appreciated.

All our [data](https://colouringlondon.org/data-extracts.html) and [code](https://github.com/colouring-cities/colouring-core) are free to download, use and share under our open licence terms. Our [open manual](https://github.com/colouring-cities/manual/wiki) also provides non-technical information on the CCRP for anyone interested in our research.

**Comment by matkoniecz** [comment]
> What are options for adding cities/towns to this e.g colouringbritain_Loughborough?

loughborough.colouringbritain.org

See https://en.wikipedia.org/wiki/Subdomain

**Comment by polly64** [comment]
@matkoniecz Great let's use this and we can give this option to other cities -
can we try zooming onto loughborough when you lick on this too

**Comment by polly64** [comment]
https://cl-production.uksouth.cloudapp.azure.com/

Hi @mdsimpson42 is colouringbritain.org seems to be going this one

**Comment by mdsimpson42** [comment]
It should be set up the same way as colouringlondon.org, so it should behave the same. I've tweaked the DNS settings, so try again in 24 hours and see if that has fixed it.

**Comment by mdsimpson42** [comment]
ColouringLondon.org and ColouringBritain.org have identical configurations, as far as I can see. They should behave the same, I have no idea why ColouringBritian.org seems to be redirecting to cl-production. I can't seem to find a solution via Google.

It is, ultimately, pointing to the right machine. I'm just not sure why the site name/URL changes. I'll keep looking into it.

**Comment by polly64** [comment]
@matkoniecz when you're back could you have a look at this many thanks

**Comment by matkoniecz** [comment]
seems to be done now
