### ISSUE TITLE
Data: Size- LiDAR/height, and adding storey info

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#172]
- [ ] Hi @MKIM1008 can you talk to @matkoniecz at how you coulod download just the garage data from the land use section?  If this is possible then could you enter 1 storey for all these locations under size

- [ ] Could you also extract the height to apex data from LIDar- free from environment agency- as in colouring London and add to map

**Comment by MKIM1008** [comment]
Download source: https://www.data.gov.uk/dataset/f0db0249-f17b-4036-9e65-309148c97ce4/national-lidar-programme

**Comment by polly64** [comment]
Hi @MKIM1008 can you extract the  building heights from the LiDAR data as UCL Energy did for us for London?

**Comment by MKIM1008** [comment]
@polly64

(Please see this tomorrow morning) I have downloaded the relevant data,  the LiDAR composite DTM 2022, and am currently reviewing the methodology. If possible, could you please provide me with the manual from UCL Energy?

**Comment by MKIM1008** [comment]
@polly64 
LiDAR extraction has been succeeded (test).

**Comment by matkoniecz** [comment]
https://colouring.london/data-extracts.html extracts are no longer completely broken

would it be sufficient for your purposes? It would require some filtering to get garages specifically

**Comment by polly64** [comment]
@matkoniecz will talk with @MKIM1008 about this (@MKIM1008 Can you remind me!). I will create a new page on the manual so Tur/Lough can add  useful links as we find them

**Comment by MKIM1008** [comment]
- [ ] @MKIM1008 to prepare LiDAR for @matkoniecz to upload onto Colouring Loughborough for Wednesday's meeting, to add to "height to apex" put under the Size category
