### ISSUE TITLE
Intermittent inability to access Colouring London site 

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#173]
Hi @matkoniecz I'm having a lot of problems accessing Colouring London/Loughborough site  on any device- often whirring until time out sign comes up. could it be to do with changing name? if you could have a look that would be great. It has been happening on and of for some time now

**Comment by matkoniecz** [comment]
I will investigate this

**Comment by polly64** [comment]
no it's ok

**Comment by polly64** [comment]
@matkoniecz maybe it was something my end, if you can't find anything shall we close?
