### ISSUE TITLE
Data: Live streaming flooding data

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#174]
Hi @MKIM1008 can you see if we can live stream data on flooding?

**Comment by MKIM1008** [comment]
@polly64 

I can see a live map on https://check-for-flooding.service.gov.uk/location?q=LE11%202tx&v=map&lyr=mv,ts,tw,ta&ext=-1.444212,52.420532,-0.929832,52.990293#Map%20for%20flooding

Charnwood Borough Council links this on their website. 

![Screenshot_20240106_111327_Chrome.jpg](https://github.com/colouring-cities/colouring-london/assets/88775529/5e225820-5397-4a26-a847-321c49d3470e)

![Screenshot_20240106_111351_Chrome.jpg](https://github.com/colouring-cities/colouring-london/assets/88775529/d17a3679-1a18-4ee2-ac58-58aedc287240)

**Comment by polly64** [comment]
@MKIM1008 great can you see if we have permission to access data live next week, thanks

**Comment by polly64** [comment]
To discuss the release of flooding data with Ordnance Survey and Environment Agency.

Open Government Licence v3.0
Crown copyright 2021

**Comment by MKIM1008** [comment]
Floord mornitoring API: https://environment.data.gov.uk/flood-monitoring/doc/reference


Relevant data:
https://www.data.gov.uk/dataset/42c31542-228d-439b-8dbe-e72135dae71c/flood-risk-areas
https://www.data.gov.uk/dataset/24542ae7-dd44-444f-b259-871c4cc43b5e/environmental-monitoring-data, air quality and noise
https://www.data.gov.uk/dataset/ac561055-3bac-4dd4-9e30-3f66bbc2896a/environmental-monitoring-points - environmental mornitoring point
