### ISSUE TITLE
'Community' section new neuroaesthetic features 

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#187]
Hi @mdsimpson42 . Based on the [Penn Center for Neuroaesthetics](https://neuroaesthetics.med.upenn.edu)' suggestions could you start revising the 'Community'  section as follows and upload to Staging, thanks. : 

 - [x] **Revise blue intro panel** to read:  'This section collects data on community views on buildings and streetscapes, and on the the location of buildings available for community use. Can you help colour the map to inform the design of our towns and cites in future?''

- [x] **Remove box** saying  'we are only capturing non-domestic information'

_________________________________________________________________________________________________

- [x] **Edit titles of subsections as below** 
- a) “Community views on buildings and streetscapes”
- b) 'Buildings with community uses

- [x] **Divide 'Community views on specific buildings and streets” **into
- Building
- Street

_________________________________________________________________________________________________

- [x] **Add question**: '_What do you feel about the exterior of this building? (if they have clicked building), or this Streetscape? (if they have clicked streetscape) Copy below for each (add this question now as draft but check wording with Penn in joint review)

- [x] ‘Hominess’ 
‘Hominess’ slider
_'How homey and relaxing does the building’s exterior feel to you?’_

- [x] ‘Coherence’ 
_'How coherent and well-organized does the building’s exterior feel to you?’_  
 
- [x] ‘Fascination’ 
_'How fascinating and complex does the building’s exterior feel to you?’_

- [x] **For each option create a 1-5 scale with “low” at one end and “high” at the other

Below each slider, which shows the user's score, add:
- [x] - a box saying how many people have contributed information.
- [x] - a box saying what the mean score is.

_________________________________________________________________________________________________

- [x] Using the color link below **create a colour key** with Blue for 'Coherence', Purple for 'Fascination', and Green for 'Hominess '(avoiding red/orange for their danger associations and yellow doesn’t stand out).

Colouring picker link: 
 [https://www.google.com/search?client=firefox-b-d&q=colour+pickerdo](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com%2Fsearch%3Fclient%3Dfirefox-b-d%26q%3Dcolour%2Bpickerdo&data=05%7C01%7Cphudson%40turing.ac.uk%7C1537416aa3c64bd4fa7b08dbd63f56b8%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638339339760390478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7 C%7C%7C&sdata=DED2C%2B6LKjhE1vHlzFmG0Iqodv9ESvl8ACzgYaL4YDQ%3D&reserved=0) 

Visualisations/map key 
- [x] - Fascination average scores for each building visualised 
- [x] - Coherence/organisation average for each building visualised
- [x] - Hominess average score for each building visualised
- [x] - Average score of all three
- [x] - NB need to add somewhere number of people entering data

Blue/Coherence 
217,231,250    162,196,250    114,165,250    60,133,250      0,94, 250
 
Purple/Fascination
243,220,250    225,162,250    213,114,250    195,62,250      180,2,250
 
Green/Hominess 
220,250,225    168,250,181    111,250,132    60,250,88        2,250,40

_________________________________________________________________________________________________

- [x] **Add link to method on 'Info' button** :
 
Coburn, A., Vartanian, O., Kenett, Y. N., Nadal, M., Hartung, F., Hayn-Leichsenring, G., ... & Chatterjee, A. (2020). Psychological and neural responses to architectural interiors. Cortex, 126, 217-241. [Link](https://www.sciencedirect.com/science/article/pii/S0010945220300332?casa_token=WiBFU-E3AGcAAAAA:6qOymtPLh1gxvgLXiVSD8OAhbOY37-ErO3NehKj4vEnhZr-uR2lCU-vFcbGDE8IN8UkI8Ug)

_________________________________________________________________________________________________

- [x] **Please tick the box if you think this kind of building/streetscape (delete where now applicable for the section) should be kept by our towns and cities for the future?**

For the building section only 
- [x] I think this because: (Tick as many as required):

- the internal layout works well
- the building feels nice to be in/use
- the building is near greenery
- this kind of building is very adaptable
- this kind of building is well built and long lasting
- Other'

For the streetscape section only 
- [x] I think this because: (Tick as many as required): 

- the street feels nice to walk down
- the layout and type of buildings makes the street feels safe
- there are interesting things to look at
- the street has greenery
- the street has public art

_________________________________________________________________________________________________

 - [x] **Are your answers above based on (tick one):
-  local knowledge of the building or street
-  professional interest in this kind of building 
-  a general impression from passing through the area
-  seeing an image of the building/streetscape 

(NB users should not be able to save their entry unless they have filled in this question 

_________________________________________________________________________________________________

 - [x] End section with '_Thank you for for your feedback! Your answers will help planners, designers and developers better understand how the form and decoration of buildings and streetscapes make people feel._'
_________________________________________________________________________________________________

**Could you move the following, thanks**:

- [x] Add a note say ' Click here (add link) for 'Planning Controls' to see status of planning applications or to record if you think this building is likely to be demolished/significantly altered' 

- [x] Remove question about planning applications.

- [x] Do you think this building should be recorded as building of special local interest? (move to 'Planning Controls' under "Possible future...")

Move "for more information..." to the end + add link_

**Comment by mdsimpson42** [comment]
I'm closing this issue for now. Any changes/additions can be added in a new issue (otherwise, it will be harder to keep track - GitHub only seems to track 'tasks' (tickboxes) in the main description of the issue, not the comments).

As the prototype changes have already been merged onto main, the latest version has been merged also.

**Comment by polly64** [comment]
Hi Carl, Johannes and Michael, can you post a translation of your questions and results here and then I can comment on them?
