### ISSUE TITLE
Users: Team membership thought capture

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-britain#195]
Via user feedback from Somerstown test project. Example UI is Strava club membership

**What this does;**

- Allow users to join a team or make a team if not already created. A team contribution will be the sum of all the user contributions, this powers the leader board / gamification. 
- How many teams can I join, eg Bloomsbury Group and Georgian Town Houses group? 

**How this works;**

- A team can be created by anyone but will be owned by no one (only Colouring London will have ability to delete a team) 

**Practical considerations**
- A team name will display the number of members it has but..
- Membership of a team will be confidential. Eg. if a school signs up then we can't expose members of that team 
- Team names need to be retractable, to guard against malicious use. Survey of London example certain teams may want to restrict membership to single user account. This would need active moderation by  community manager/admin. 
- Users can leave a team to join another team but contributions made during that team will remain with that team (unless replaced by other user) 
- When would this be implemented, could users choose to retrospectively assign all their contributions to team (eg Somerstown members) 
- This would be part of sign up work flow ie. Collect user data hit return > Prompt says ok you're registered as a individual would you like to contribute to a team? > If yes explanation of this and join/create, If no get colouring. 
- Needs a report team button (to flag malicious use / name), team name creator needs logging for same reason

**Comment by polly64** [comment]
@mdsimpson42 close and add link to gamification issue

**Comment by mdsimpson42** [comment]
Link to this issue added to https://github.com/colouring-cities/colouring-core/issues/1303
