### ISSUE TITLE
Add multiple "Extension" options in Team category

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-britain#232]
With the extension we should rename extension to be 'Major extension, restoration, retrofit or refurbishment?'

When you click on this section it should then give option to tick any of these 4 options separately or all. Once ticked it should give the option to fill in all subcategories as we have them for the main building - to autolink to 'Age also

**Comment by mdsimpson42** [comment]
We now have the "main building" versus "most significant extension" data in this category. 
Closing this for now. Additions, changes can be added in new issues.
