### ISSUE TITLE
create prompt for where source is still correct  if a subcategory is change d

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#246]
if category is changed and related source not create prompt to say' is this still the right source?'

**Comment by mdsimpson42** [comment]
No, but it would seem connected to #209?

**Comment by matkoniecz** [comment]
Some fields have source info to be filled.

Maybe it refers to case where user edits category and there is source filled already?

![screen03](https://github.com/colouring-cities/colouring-britain/assets/899988/37764677-a24c-45f7-bef6-055a6e6b2212)

**Comment by polly64** [comment]
refers to the 209 and so one of them can be closed -

**Comment by matkoniecz** [comment]
clearing source seems more reasonable than prompt on each edit

**Comment by matkoniecz** [comment]
see #209

**Comment by polly64** [comment]
@matkoniecz ok great if you or @mdsimpson42 could go with that
