### ISSUE TITLE
Do not permit data entry deletion unless replacement given

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#249]
@tomalrussell @edwardchalstrey1 Just noticed the block on deletion of other people's edits doesn't seem to be activated - just checked age data. You seem to be able to remove by deleting and save. Ed we had an issue a while ago and agreed that you shouldn't be able to delete an edit unless you replaced with something else to reduce chance of malicious behaviour. If we could possibly look at would be great

**Comment by mdsimpson42** [comment]
Duplicate of #240?

**Comment by polly64** [comment]
@mdsimpson42 yes

**Comment by mdsimpson42** [comment]
Duplicate of https://github.com/colouring-cities/colouring-britain/issues/240
