### ISSUE TITLE
need autosave all Team categories & won't let save on Dynamics

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#252]
won't let you save

**Comment by mdsimpson42** [comment]
Connected to #248? Again, there is no Dynamics category any more...
Either need more information or close this issue (can create a new issue if we rediscover the bug).

**Comment by polly64** [comment]
@mdsimpson42 dynamics now under age/lifespan

**Comment by mdsimpson42** [comment]
"Won't let save on Dynamics" is duplicate of https://github.com/colouring-cities/colouring-britain/issues/248.
Team category has been reworked, so presumably no longer relevant.
