### ISSUE TITLE
Update Team section to support multiple extensions per building

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-britain#255]
We need to be able to capture data on whole building and on all extensions at same time or separately . i.e. rather than having an either/or - meaning you have to state the whole process again for each extension.

- [ ] add character limits where appropriate

**Comment by mdsimpson42** [comment]
We now have data for 'main building' and 'most significant extension'. Expanding to support multiple extensions is a bigger piece of work, which we decided wasn't a priority. As for character limits, we currently no longer allow free-text entry.

I'd say close this for now and we'll create new issue(s) if/when we want to make further changes.
