### ISSUE TITLE
Make "View" mode the default when selecting a new building

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-britain#262]
Currently when in "Edit" mode, clicking another building will mean that it's opened in Edit mode automatically, but might be better/nicer/safer to default to "View mode".

**Comment by mdsimpson42** [comment]
It hasn't been done. I'm not sure how easy it would be to do. 
If we still want it done, add it to the list, otherwise close it.

**Comment by polly64** [comment]
@mdsimpson42 let's try a pop up box that asks if you want to edit in light background mode

**Comment by mdsimpson42** [comment]
That's not the issue here. Are you thinking of #247?

**Comment by polly64** [comment]
@mdsimpson42 yes I see- actually if you are in edit mode I think you want to stay in edit mode
