### ISSUE TITLE
repository and Colouring London renaming

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-britain#266]
@mdsimpson42  - repository got renamed as requested by @polly64 

as far as I know it has no strong technical impact, but remotes at staging/production will need to be changed (and at our computers...)

maybe some documentation should be changed

**Comment by matkoniecz** [comment]
https://github.com/colouring-cities/colouring-london remains a redirect, what is nice

**Comment by matkoniecz** [comment]
I changed repository description (about section on Github at https://github.com/colouring-cities/colouring-britain ) to

> Collecting data on Britain's buildings

@polly64 (pretty sure about this, but review welcome)

**Comment by polly64** [comment]
@matkoniecz  great thanks

**Comment by polly64** [comment]
@mdsimpson42   can you review above so we change asap throughout thanks
@matkoniecz so is new url for site working colouring,britain.org? If i search for that Colouring London comes up. Would you be able to  change  the London name on Colouring London site to Colouring Britain? and make me land still on london? and then send a url for loughborough?

**Comment by polly64** [comment]
@taimaz22 it would be good to do some publicity around rebranding when Mateusz and Mike are ready and postcodes, loughborough and london url's and the INSPIRE/OSOML open datset for e.midlands etc are all up.

**Comment by taimaz22** [comment]
Sounds great Polly. I will email the marketing team to set up a meeting with them for us towards the end of January. I will copy you in all the emails.

**Comment by matkoniecz** [comment]
Similarly: https://github.com/colouring-cities/colouring-core/blob/7f33c946762ac311be62f5282b8803ed8d056e67/app/src/frontendRoute.tsx#L102 should be also changed and maybe it should be configurable in general per platform.

**Comment by polly64** [comment]
@matkoniecz I think everything as you say should be changed to Colouring Britain wherever we can,  but we still need to be able to search for Colouring London with old domain name and with new name london.colouring.britain.org. Good if you cam agree with @mdsimpson42 on this tomorrow

**Comment by matkoniecz** [comment]
> We are promoting https://twitter.com/colouringlondon (it is a bit hidden)

> Should it stay there, be configurable per platform (so they can put own handle), be removed? Something else?

removed
