### ISSUE TITLE
Data: Solar panels 

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#269]
@MKIM1008 could you see if council has any data on buildings that have solar panels + building that have potential for solar panels thanks

**Comment by MKIM1008** [comment]
I will include the data availability in the enquiry list to the council. Otherwise, we need to contact the Leicestershire County Council as a solar panel partner. https://www.charnwood.gov.uk/pages/solartogether

**Comment by MKIM1008** [comment]
Relevant data:
https://www.data.gov.uk/dataset/2057327e-d1f2-4f63-894f-72fc75235188/great-british-insulation-scheme

**Comment by MKIM1008** [comment]
@polly64 

In EPC & DEC data

SOLAR_WATER_HEATING_FLAG
RENEWABLE_SOURCES (including solar panels)

**Comment by polly64** [comment]
@MKIM1008 let's adjust core text to reflect this
