### ISSUE TITLE
Is colouring-core/app/src/frontend/pages/about.tsx used somewhere? Should it be updated or removed?

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-britain#278]
I see no obvious place where it is used, it may be a dead code.

See https://github.com/colouring-cities/colouring-core/blob/7f33c946762ac311be62f5282b8803ed8d056e67/app/src/frontend/pages/about.tsx#L28

For example

>Colouring Cities is being designed and built by the Centre for Advanced Spatial
>Analysis (CASA), University College London and funded by Historic England.
>Ordnance Survey is providing building footprints required to collect the data,
>facilitated by the GLA, and giving access to its API and technical support. It
> will launch in 2019.

@polly64 Do you remember where it used to be/should be? Or maybe do you remember removing it?

**Comment by polly64** [comment]
@matkoniecz we don't need this anymore can you close?

**Comment by matkoniecz** [comment]
@polly64 If we do not it anymore then I will remove it from currrent code version and then close.

**Comment by polly64** [comment]
@matkoniecz great
