### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by daveox99** [colouring-cities/colouring-britain#284]
**Describe the problem**

**To Reproduce**

**Expected behavior**
A short description of what you expected to happen.

**Screenshots**
If it helps to explain the problem, add screenshots.

**More information**
Add any other context about the problem here - which browsers or devices show it, whether it's only started happening recently...

Have not used Colouring Britain for some time. Tried to use today and during Login
Entered my id "do1950"
Entered my password
Tells me that my userid does not exist
Go to Sign up
Enter userid do1950
Enter email daveoxman@aol.com (twice) and password.
Click signup and it tells me that email already registered!

Gave up!

**Comment by matkoniecz** [comment]
@daveox99 Have you tried using https://colouring.london/forgotten-password.html ?

**Comment by daveox99** [comment]
I have now used this link and entered my email address and a new password.When I try and log in using my username (do1950) (it will not allow me to use my email address) it says "The username does not exist in the system"
RegardsDave Oxman

    On Wednesday, 24 January 2024 at 12:22:24 GMT, Mateusz Konieczny ***@***.***> wrote:  
 
 


@daveox99 Have you tried using https://colouring.london/forgotten-password.html ?

**Comment by matkoniecz** [comment]
@daveox99 It seems that there is user `d01950` (with number zero, not letter) while there is no user `do1950`

Can you retry with zero used as a second character?

**Comment by matkoniecz** [comment]
seems to be resolved
