### ISSUE TITLE
Testing Companies House API

### ISSUE THREAD

**Issue by MKIM1008** [colouring-cities/colouring-britain#295]
https://developer.company-information.service.gov.uk/overview

@matkoniecz,

Could you possibly let me know if you think this API allows to stream bulk data or if you think it's gonna allow to stream one entry of time?

**Comment by matkoniecz** [comment]
I would consider using https://www.gov.uk/guidance/companies-house-data-products

How many entries are in their database? Downloading them one by one via API is unlikely to work well (may be blocked and may be not fast enough to iterate through all entries in one month). Also, would take more work to setup and run than using the public snapshots.

**Comment by matkoniecz** [comment]
Though wait: there is also https://developer-specs.company-information.service.gov.uk/streaming-api/reference

which part of that would be relevant and visualised/available/relevant for CL?

**Comment by MKIM1008** [comment]
> I would consider using https://www.gov.uk/guidance/companies-house-data-products
> 
> How many entries are in their database? Downloading them one by one via API is unlikely to work well (may be blocked and may be not fast enough to iterate through all entries in one month). Also, would take more work to setup and run than using the public snapshots.

@matkoniecz,
For Loughborough there are around 4000 cases, and in the entire files, one of the 7 files includes 850000 cases.

**Comment by matkoniecz** [comment]
https://developer-specs.company-information.service.gov.uk/streaming-api/guides/authentication is the next step to look into it
