### ISSUE TITLE
Sidebar linking to nonexisting wiki page for contributor agreement

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-britain#309]
sidebar links to https://github.com/colouring-cities/manual/wiki/C1.-Protocols,-codes-of-conduct-&-data-sharing-agreements#ccrp-contributor--data-user-data-accuracy--ethical-use-agreement

registration page links to https://colouringlondon.org/contributor-agreement.html

@polly64 Both should link to https://colouringlondon.org/contributor-agreement.html - right?

**Comment by matkoniecz** [comment]
note that this applies also to colouring-core

There is a default contributor agreement and it is not linked from sidebar

**Comment by mdsimpson42** [comment]
Confirmed. The first link does not exist, it asks you to create a new page on the Wiki. Was the page moved or renamed? 
It is actually linked twice from the sidebar under "Contributor Agreement" and "Data Accuracy and Use Agreement". Should those two be combined, or should they be separate?

The link on the registration page is a relative link, so it will link to a page on the local Colouring Cities platform itself. 

Do we want these kinds of info pages to be part of the platform, or on GitHub? (Or on a central site like ColouringCities.org) It's probably best not to have this kind of info in multiple places, in case we need to update it?

**Comment by mdsimpson42** [comment]
As part of the documentation revamp, pages like the contributor agreement have been moved to the manual/wiki. I've deleted them and updated the links on the sidebar and relevant pages. These fixes will soon be merged onto Core and will be picked up in the next merge from Core to Britain.
