### ISSUE TITLE
Colouring Britain checklist

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#318]
Hi @matkoniecz could you possibly try work through the check list of outstanding items. I'll keep adding to them as i find them. Could you tick off when they are done so i can keep track, thanks

- ~~[x] Add correct intro text to Colouring Britain~~ (https://github.com/colouring-cities/colouring-core/issues/1291)
- [ ] Hide Newcastle university logo - university logos are only included where free resources and/or research time have been contributed by a university 

- ~~[x] Do not let users save edits in any section unless they have filled in source type, and source link if applicable~~ (https://github.com/colouring-cities/colouring-britain/issues/189)
- Hi Mateusz

**Comment by matkoniecz** [comment]
@polly64 

> Hide Newcastle university logo

Maybe all logos should be removed in upstream (colouring-core) repository and it should be maintained only in colouring-britain?

Maybe it should be moved to config to enable other cities/countries to easily list their partners?

**Comment by polly64** [comment]
@matkoniecz yes agree thanks

**Comment by matkoniecz** [comment]
> Do not let users save edits in any section unless they have filled in source type, and source link if applicable

Do you remember some example affected fields? Or fields where such check exists already? (I can look for them but if you just remember them...)

**Comment by polly64** [comment]
Hi @matkoniecz ,  @mdsimpson42 is do a detailed check on this so have reassigned

**Comment by mdsimpson42** [comment]
I'm ticking off the first and forth items on the checklist as there are already issue for these

**Comment by matkoniecz** [comment]
> I'm ticking off the first and fourth items on the checklist as there are already issues for these.

Can you maybe link them in the body of issue? (or in comment?)

**Comment by polly64** [comment]
@mdsimpson42 we seem to have lost people on this https://www.turing.ac.uk/research/research-projects/colouring-cities-research-programme, this is where Newcastle would be credited, and on open manual Colouring Britain page. Were you on this before, could you send me your pic if not and I will ask them to upload , and title at Newcastle
