### ISSUE TITLE
Disaster management tool not colouring on live site

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#321]
Disaster management tool not colouring on live site
Under 'resilience section'

**Comment by matkoniecz** [comment]
it is appearing for me, bot in staging and on production

can you link affected building? or which fields you changed?

Ideally a screenshot including building properties and legend in top right

**Comment by polly64** [comment]
@matkoniecz thanks - I see that there is disaster info on live site - can we remove it all as shouldn't be there?

**Comment by matkoniecz** [comment]
Is it not ready to be officially released? Or is it supposed to be disabled for London?

**Comment by polly64** [comment]
it is meant to be officially released and available for UK - but it looks like these colours are tests

**Comment by matkoniecz** [comment]
Are there any colours on live production site? I see some in London on staging but it is fine to test there.

(I can go into database to check thoroughly for any data being present on live site)
