### ISSUE TITLE
cambridge

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#354]
Hi @matkoniecz this is where I will put comments re age and history section with Cambridge , 

- [ ] add plus buttons for extensions, refurb and retrofit 
- [ ] Date of significant refurbishment
- [ ] Add ' specialist website' in dropdown of source type for everywhere
- [ ] add to drop down of sources to say 'local history website' and 'other website'
- [ ] Under 'Age' historical source drop down  include' local history website'
- [ ] when post code is searched for it automatically detect map with most edits and view this, other we send up landing on blank maps though a lot of data for an area may have been added?MOVE to international
- [ ] we will need to Merge Victorian and Edwardian for architectural style and just put all data from both in same class
- [ ] problem with some blocks not split
- [ ] provide additional overture's OSM and microsoft collation layer on staging
- [ ] we will need splitting tool for cambridge colleges

- [ ] Change colours  and descriptions on  Architectural period (with colours better matching)
- [ ] Change order
2000 onwards - Yellow 
1980s and 90s - Orange  
Post war - Bright Red 
 Interwar - Deep Red 
Victorian/Edwardian - Blue 
 Georgian -Bright Green  
Late Medieval/Tudor -1067-1603 use 'Medieval' colour from Architectural period'
Early Medieval - use 410-1066 '<1700 colour
Roman - use bright grey

- [ ] How can we highlight where parcels need splitting?
- [ ] How can we manually split polygons to add different ages? 
- [ ] Coloured a building but can't undo without choosing a dropdown
- [ ] Need possibility in layers of removing buildings so you can see underneath 
<img width="216" alt="Screenshot 2024-09-23 at 20 00 57" src="https://github.com/user-attachments/assets/19c7603c-f43a-4525-891f-2dfd376e12ce">
<img width="220" alt="Screenshot 2024-09-23 at 20 00 47" src="https://github.com/user-attachments/assets/4ea9d249-0bb8-4aa1-981b-1f8ecf7d93dd">

**Comment by matkoniecz** [comment]
```
Change order
2000 onwards - Yellow
1980s and 90s - Orange
Post war - Bright Red
Interwar - Deep Red
Victorian/Edwardian - Pale Blue
Georgian -Bright Green
Late Medieval/Tudor -1067-1603 use 'Medieval' colour from Architectural period'
Early Medieval - use 410-1066 '<1700 colour
Roman - use bright grey
```

1) changing order and colours is easy, changing timespans is problematic as it is unclear what should be done with existing data

2) should Stuart/Tudor really have the same colour

3) Stuart/Tudor/Medieval really should have greater variety, I think

![screen01](https://github.com/user-attachments/assets/e0294637-05bb-4f3f-8008-fc1969a5e8ff)

**Comment by polly64** [comment]
@matkoniecz have updated list could we work on this together tomorrow at all realise i do need stuff soon

**Comment by polly64** [comment]
London not automatically showing architectural style when i scroll across from cambridge and vice versa

**Comment by polly64** [comment]
glitch , can't get rid of this
<img width="548" alt="Screenshot 2024-09-30 at 22 42 25" src="https://github.com/user-attachments/assets/e30ca7fa-d51a-4dcc-adbe-e5e8ecf9e10b">

**Comment by polly64** [comment]
@matkoniecz add boundary line around cambridge
