### ISSUE TITLE
Correction of errors on footprints

### ISSUE THREAD

**Issue by MKIM1008** [colouring-cities/colouring-britain#357]
@matkoniecz, 

Could you develop drawing systems on the platform: 
a. open building footprint correction tool;
b. academic moderation tool - line drawing - it is to put/seperate colours about specific building ages on extended or renovated building polygons.

**Comment by MKIM1008** [comment]
For b. suggest for snapping and connecting vertices.

**Comment by polly64** [comment]
Hi @matkoniecz 

could you add the correction feature and push it up to top place on the agenda - thanks

- [ ] Add new layer called Footprint improvement tool or other similar
- [ ] Add colour key with pink meaning -  detach from adjacent polygon
- [ ] bright red meaning - split
- [ ] bright  - remove spikes
- [ ] Other
and obviously add anything else you need


could you at the same time swap the two main categories/tiles for urban context  and green/water context so green sits on 
current urban tile and rename  'green/water context'

**Comment by MKIM1008** [comment]
Building polygon layers comparison

- Spatial extent: Overlap area, containment, adjacency, or buffer distances.

- Geometric properties: Area, perimeter, shape similarity (e.g., convexity, elongation).

- Attribute values: Compare associated thematic data (e.g., land use type, population density).

Area Overlap: 
Calculate the percentage of overlap between polygons in both layers.

Spatial Metrics:
- Distance measures: Minimum distance between polygons.

- Shape similarity: Metrics like the Jaccard Index or Dice coefficient can quantify similarity between shapes.

Statistics:
- Similarity indices (e.g., Jaccard similarity) 

- Weighted Correlation

- Principal Component Analysis (PCA)

In progress

**Comment by MKIM1008** [comment]
LiDar
https://environment.data.gov.uk/survey

Google Open Buildings
https://sites.research.google/gr/open-buildings/

Open Buildings 2.5D Temporal dataset
https://colab.research.google.com/github/google-research/google-research/blob/master/building_detection/open_buildings_temporal_download_region_geotiffs.ipynb#scrollTo=I6_WXApNUGUu

**Comment by MKIM1008** [comment]
> Hi @matkoniecz
> 
> could you add the correction feature and push it up to top place on the agenda - thanks
> 
> * [ ]  Add new layer called Footprint improvement tool or other similar -> Building footprint geometry issues
> * [ ]  pink meaning -  detach from adjacent polygon 
> * [ ]  bright red meaning - split
> * [ ]  bright green- remove spikes
> * [ ]  bright turquoise - adjacent building missing
> * [ ]  bright orange - two or more buildings merged in one polygon
> * [ ]  Other
>   and obviously add anything else you need

We need to put it in the layers and the same title in the **location** section, and building footprint section.

**Comment by matkoniecz** [comment]
![screen](https://github.com/user-attachments/assets/fa4da8dc-976f-4b89-b361-05ac277778dd)
![screen02](https://github.com/user-attachments/assets/01892743-ccaf-4111-ac7f-5b391f5decd7)
![screen01](https://github.com/user-attachments/assets/40171e7e-0830-4b88-aa86-3ad04690f29a)

**Comment by matkoniecz** [comment]
I see that orange is missing

**Comment by matkoniecz** [comment]
![screen03](https://github.com/user-attachments/assets/1433ce5c-e5be-4951-9298-88043cc7e9d0)

**Comment by matkoniecz** [comment]
What about current pink contents? Do we want to lose ability to mark that building should stop being glued to another one?

Also, maybe "Footprint needs to be split into major different construction periods'" can be yellow, " Footprint needs to be divided into 2 parts" can be orange and "Footprint needs to be divided into more than 2 parts" can be red with logical progression of problems from lesser to worse?

And maybe "Footprint needs to be split into major different construction periods'" can be "Footprint is one building but needs to be split into major different construction periods'"?

**Comment by matkoniecz** [comment]
@polly64 It is much better to post a new comment - this way it is clear which part is comment and which I wrote.

Also, it is easy to miss comment being edited (luckily I was closing tabs and seen this one)

**Comment by polly64** [comment]
sure

**Comment by matkoniecz** [comment]
new version: ![screen05](https://github.com/user-attachments/assets/eb5f2bcc-e81a-4cc0-b9c0-a3cf41e82650)

**Comment by matkoniecz** [comment]
@polly64 Is above OK?

**Comment by matkoniecz** [comment]
remove: "different" "footprint"

**Comment by matkoniecz** [comment]
Please record inaccuracies in building footprints.
