### ISSUE TITLE
Switching on and off current building polygons

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#359]
@matkoniecz 

Can we have an icon (similar to size of plus and minus signs, and you can have buildings off or on - this links to the layer issue?

Could you suggest ideas for an icon too? @fallipalaiologou suggest an icon outside the layer dropdown that is v easy to see

**Comment by matkoniecz** [comment]
I though about putting it in layer options, without an icon

**Comment by matkoniecz** [comment]
like this, on assumption that it is relatively advanced functionality used only by experts or for special purposes - new contributors would be likely confused by buildings disappearing

![screen11](https://github.com/user-attachments/assets/70a738e0-ae47-41f8-9a18-096c9e46626c)

**Comment by polly64** [comment]
let's try your suggestion for moment - can you implement easily?

**Comment by matkoniecz** [comment]
done in https://github.com/colouring-cities/colouring-core/pull/1412 - highlight of buidling selection stays
