### ISSUE TITLE
Change needed to main categories

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-britain#366]
The latest changes to the categories need to be deployed to Colouring Britain. (i.e. the Urban Infrastructure category needs to be swapped with the Green/Water Infrastructure category - which should read Green/Water rather than Water/Green). 

These changes have been made to the code, but need to be deployed to the production server, but the production server is currently on a different branch with unsaved changes. Can we confirm that it is OK to switch this back to colouring-britian/master and deploy the latest changes, or is this going to affect existing work?

**Comment by matkoniecz** [comment]
https://github.com/colouring-cities/colouring-core/issues/1411 is related

copying from email:

this branch included commit with smaller text size, not included into main repository
I added it as I was asked to quickly release new version and it was clearly broken on my computer

it does not include it anymore as apparently it is not widely reproducible

this branch may be safely removed now

2) yes, better fix would be needed - and investigating what triggers it
is it about Firefox? Fonts available on my Lubuntu OS?
Screen size? Something else?

**Comment by matkoniecz** [comment]
> Can we confirm that it is OK to switch this back to colouring-britian/master and deploy the latest changes

I believe that answer is "yes"
