### ISSUE TITLE
Are you available to join the re-meeting now? (Mateusz)

### ISSUE THREAD

**Issue by MKIM1008** [colouring-cities/colouring-britain#388]
@matkoniecz 

https://us04web.zoom.us/j/77268941264?pwd=l3niU3ZLaypWpUhNPE590tBYOzbZyW.1
Pass: vJJ9Zu

**Comment by matkoniecz** [comment]
joined

**Comment by matkoniecz** [comment]
"Waiting for the host to start the meeting."
