### ISSUE TITLE
Move "Listed" status (Planning section) from Core to London

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-britain#54]
Presumably, the idea of Grade 1-2 listed buildings is unique to the UK, therefore it shouldn't be included in the core platform, but should be part of Colouring London/Britain.

**Comment by polly64** [comment]
@mdsimpson42 yes please could you do this and close issues thanks

**Comment by mdsimpson42** [comment]
Change to "protected status" on Core and allow customisation.
