### ISSUE TITLE
Data- Age - Colouring Loughborough 

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#62]
@MKIM1008 could you extract Age data at block and property level from EPCs?
Could you add to OSMM as allowed under uni licence  and upload image of this here so I can see how it looks?

Also can you ask @matkoniecz how you can add data directly to help allow MK to concentrate on solving complex technical issues

**Comment by polly64** [comment]
@taimaz22 Think worth contacting Alison Mott here https://www.lboro-history-heritage.org.uk/, and also copy email to https://www.lboro-history-heritage.org.uk/projects/loughborough-library-local-studies-group/
Looks like huge amount of knowledge will be held here.  If you could send link to Colouring London age and say this is what you are working on and might they be interested in helping after Christmas with age  and land use data and that no special technical expertise is needed. im happy to give an introductory chat for anyone who might be interested

**Comment by MKIM1008** [comment]
> @MKIM1008 could you extract Age data at block and property level from EPCs? Could you add to OSMM as allowed under uni licence and upload image of this here so I can see how it looks?
> 
> Also can you ask @matkoniecz how you can add data directly to help allow MK to concentrate on solving complex technical issues

@polly64 @matkoniecz I will look at the data from EPCs and upload the image adding it to OSMM in this post soon. 

@ Taimaz We've met Alison at Loughborough Heritage Forum and she might remember TIH project showing interests on us and introducing Dr. Robert Knight's work now at UCL.

**Comment by MKIM1008** [comment]
@polly64 

Apologies for the late reply, I've been struggling with a UPRN issue and a project report ahead of schedule. 

I've resolved the UPRN problem and am now sorting out the EPC age data, which shows irregular construction years. 

May I present the GIS image in two parts: 1) current construction years, and 2) adjusted for a regular age range?

![image](https://github.com/colouring-cities/colouring-london/assets/88775529/80bb2bd7-cf91-47bd-95dd-67e9f9ab3a81)
![Untitled](https://github.com/colouring-cities/colouring-london/assets/88775529/f474fb6b-9de3-4672-884e-a6d53a351732)

**Comment by MKIM1008** [comment]
OS Open Linked Identifiers

1) Without road: OS Open Toid (OSMM topography layer) + UPRNs -> An EPC average in the street block polygon (Toid)
![image](https://github.com/colouring-cities/colouring-london/assets/88775529/4bc495a1-4d41-45cb-be08-5b06285656da)

2) With road: OS Open Toid (OSMM highways network) + UPRNs -> An EPC average in the road block polygon (Toid)
![image](https://github.com/colouring-cities/colouring-london/assets/88775529/13a47c33-d790-4d5e-88f2-f5b5e05bf736)

**Comment by polly64** [comment]
> @polly64
> 
> Apologies for the late reply, I've been struggling with a UPRN issue and a project report ahead of schedule.
> 
> I've resolved the UPRN problem and visualise the age data from EPC, which shows irregular construction year bands.
> 
> * Process: OSMM -> UPRN join -> Age join (UPRN centred)
> * The white box represents a null value for the age data.
> 
> **Domestic EPC - age (property)** ![image](https://private-user-images.githubusercontent.com/88775529/289355942-e353f9ef-ab4d-47d6-a086-3f4a407804af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTYzMzksIm5iZiI6MTcwMjI5NjAzOSwicGF0aCI6Ii84ODc3NTUyOS8yODkzNTU5NDItZTM1M2Y5ZWYtYWI0ZC00N2Q2LWEwODYtM2Y0YTQwNzgwNGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2OWNmNTMzYzJiZmYxNmZmMDYxMzMzM2Q4Y2JmZWRmZTg2NDAzYjVkNmQwNGI5YWJmZTRiYjBkN2FjOGIzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bNCWxazmbHP6d-Sy9TF5mZkTykYdwegytuEiidAhezU) ![image](https://private-user-images.githubusercontent.com/88775529/289355900-7467923f-f575-4500-b587-1824a2145568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTYzMzksIm5iZiI6MTcwMjI5NjAzOSwicGF0aCI6Ii84ODc3NTUyOS8yODkzNTU5MDAtNzQ2NzkyM2YtZjU3NS00NTAwLWI1ODctMTgyNGEyMTQ1NTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZDA1NWYxMWY3NTE4ZTExNjZhMmY4OWQ2OTJiOGUyYTYyZTcxZDdjY2MyOGMwMjYzMWJkMGI5MjU1MGFhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HB-4i0VAxeLB7basRCMSlBhdrzPnLh5UBwZ_DAHI-vI)
> 
> **Domestic EPC - age (block) - building (OSLM) & street** It appears in the vision that the property groups have been developed in different periods by the (building & street) blocks - trying to make some polygon examples with the average.
> 
> *The calculating rule of average age would be required with old maps analysis. - as spatial inference

@MKIM1008 oh I forgot about this really annoying way they classify stuff. You can't add to the CCRP age map classes easily because of this 


<img width="459" alt="Screenshot 2023-12-11 at 12 16 56" src="https://github.com/colouring-cities/colouring-london/assets/42236514/d85a8dff-5465-4586-aaad-94e0d3bdada9">

You can add earliest and latest start date here as earliest and latest , and take the date in the middle of the range for best estimate. Once i can access the map I can use street view to check the dates by eye and pick up any stuff that looks v wrong. Then we can ask historians for their expert checking. 

________________________________

here is to link to the Architectural period category https://colouringlondon.org/edit/age/2407428

<img width="815" alt="Screenshot 2023-12-11 at 12 15 53" src="https://github.com/colouring-cities/colouring-london/assets/42236514/1ca49880-c6b5-4e12-9909-fb5c52d66dc5">

Pre 1900 - classify as 'Victorian' but remove listed buildings as this covers buildings before 1840
1900-29 - classify as WW1-WW11 but I will spot check
1930-49  classify WW1-WW11 
1950-66 classify Post War
1967-75 classify Post War
1983-90 classify late 20thc
1991-95 classify late 20thc
1996-2002 classify late 20thc
2003-2006 classify early 20thc
2007 onwards classify early 20thc
2007-11 classify early 20thc
20012 onwards classify early 20thc

**Comment by MKIM1008** [comment]
@polly64 

Thank you! I am adding one more image of Energy efficiency rate (in OSMM)

Process: OSMM -> UPRN join -> Energy efficiency rate join (UPRN centred)
The white box represents a null value for the Energy efficiency rate data - not domestic buildings.

* Average caculation done, and needs to decide what polygons would be used. 

![image](https://github.com/colouring-cities/colouring-london/assets/88775529/b504f4dc-3a1b-433b-9487-d4cfc95cde0a)

**Comment by polly64** [comment]
@MKIM1008 could you possibly recolour the age ones similar to this one with v different colours and post now- then I can see if I can see significant errors just from the footprint shape

**Comment by MKIM1008** [comment]
@polly64 

Age from EPC with the Architectural Style < overlapped second 1914 was to 1915
![image](https://github.com/colouring-cities/colouring-london/assets/88775529/db76fab8-3371-4251-adda-295c589a84d5)

Age from EPC with CLondon classification
![image](https://github.com/colouring-cities/colouring-london/assets/88775529/69bb983f-1f66-47a2-9446-631b71227a51)

**Comment by polly64** [comment]
Hi  @matkoniecz are you back working today? happy New year!

**Comment by matkoniecz** [comment]
@polly64 Yes, though only now I reached this specific issue

**Comment by matkoniecz** [comment]
I think it is imported now? Please reopen or create a new issue if work remains to be done

**Comment by MKIM1008** [comment]
@polly64 
https://www.mapserve.co.uk/blog/how-to-determine-building-age-using-os-ngd-information

**Comment by polly64** [comment]
Hi Mihyun unlikely to as good as our age data method but interesting, don't really understand how you determine it from the blog info?

**Comment by MKIM1008** [comment]
@polly64 @matkoniecz 

1) EPC (Domestic) data contains different age values for the same building reference number/UPRN.
How should we proceed with visualising this on the building polygons?
For example, should we prioritise the oldest construction age?
![Image](https://github.com/user-attachments/assets/93c2abed-9889-49c3-80b3-fb0d042c6c03)

2) I’ve separated the starting and ending years from the Construction Age Band in the EPC–Domestic dataset. - I thought it would be useful to include these as separate columns in the Colouring Britain dataset for clarity and consistency.

**Comment by polly64** [comment]
@MKIM1008 just send me a meeting link - don't think we can do this as looks like start of construction and end of construction dates we need ti think to have 'earliest start estimate' and 'latest estimate' but let's chat

**Comment by MKIM1008** [comment]
> [@MKIM1008](https://github.com/MKIM1008) just send me a meeting link - don't think we can do this as looks like start of construction and end of construction dates we need ti think to have 'earliest start estimate' and 'latest estimate' but let's chat

Yes, Polly I will share the invite with you shortly. They are Starting and Ending Construction ages to upload to the platform and I will change the column names.
