### ISSUE TITLE
BulkData: Uploading system

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-britain#77]
HOTOSM have created a nice system for this which is open source,. To investigate: Can be adapted for CL bulk uploads

https://tasks.openstreetmap.us/about

**Comment by polly64** [comment]
@matkoniecz is this helpful for bulk upload moderation?

**Comment by matkoniecz** [comment]
not really, that is for coordination of low-skill manual contributors

**Comment by matkoniecz** [comment]
in manual?

**Comment by polly64** [comment]
could you add to technical page thanks https://github.com/colouring-cities/manual/wiki/G1.-TECHNICAL-OVERVIEW
do and a section for 'useful tools' or something like that if you think helpful and if you could also add a link from initial 'content' items  at the start of the page to the new section that would be great

**Comment by matkoniecz** [comment]
Tasking Manager is quite tightly integrated with OpenStreetMap and is primarily/almost entirely for splitting area for digitizing aerial imagery.

So it is a quite different from importing external data in bulk.

https://maproulette.org/ is including some import tools and can be useful as inspiration, but code is also likely not going to be directly usable as it is also tightly integrated with OpenStreetMap.
