### ISSUE TITLE
BulkData: Datasets for manual upload for launch

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-britain#78]
List of data potential sets identified, for colouring-cities/colouring-core#299  > Status of data > Time to process/upload in days;

   
1. - [x] HE Listed buildings bulk data > ~~Request licence sign off~~ 
2. - [ ] Listed buildings borough specific data > See colouring-cities/colouring-core#538 
3. - [ ] Land use data from functional sites > Needs licence sign off with HMLR
4. - [ ] Building use and ownership data from London Land Commission > 
5. - [ ] Conservation areas data update > Ready for upload
6. - [x] Building attachment data >~~ Request from UCL Energy~~ > Agreed to upload 
7. - [x] Carb2 > ~~Request from UCL Energy~~ Not possible due to licence
8. - [ ] SCU Height data > ~~Request from UCL Energy~~ > Agreed to upload
9. - [x] Building Mix data > ~~Request from UCL Energy~~ Not possible due to licence
10. - [ ] Accessibility data colouring-cities/colouring-core#315  > Can be via API 
11. - [ ] Materials data (can be prepopulated from listed buildings data)  
12. - [ ] London tree [data](https://data.london.gov.uk/dataset/local-authority-maintained-trees) to 
13. - [ ] Wiki buildings [data](https://en.wikipedia.org/wiki/Category:Buildings_and_structures_in_London)? 

14. - [ ] OS Green space - to calculate distance to nearest public greenspace
15. - [ ] Land use / address / floorspace / greenspace / demolition data from [LDD](https://data.london.gov.uk/dataset/planning-permissions-on-the-london-development-database--ldd-) > OGL v3 
16. - [ ] DEC data > ~~Request from UCL Energy~~ > Agreed to upload

**Comment by polly64** [comment]
may be useful ti check for loughborough
