### ISSUE TITLE
UI/UX: Adding source column to database 

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-britain#79]
@tomalrussell We have been discussing adding source to data. Generally this will be per category but some will be per field/sub-category. In terms of adding to the db do you have a preference on this? Thoughts;

- Source into `buildings` format `category_source` new column per source. This would add around 10 columns taking the total table width to somewhere around ~90 
- Separate `sources` table same format `category_source`

There will also be a requirement to only save data if source field is completed, I think that is a front end check? 

We will have a similar issue (of expanding the table or creating separate table) for the fields we are adding a verification too, but there will be far fewer of these. 

This issue links to;
- colouring-cities/colouring-core#326 colouring-cities/colouring-core#298 colouring-cities/colouring-core#347

**Comment by polly64** [comment]
Hi @matkoniecz has this issue been dealt with?

**Comment by matkoniecz** [comment]
It seems that occasionally we have ability to provide source, saved together with other building properties.
