### ISSUE TITLE
UI/UX: Autocomplete text 

### ISSUE THREAD

**Issue by dominijk** [colouring-cities/colouring-britain#80]
### What it does?
Prevents issues with free text and malicious entry, links to moderation mechanism and linked
fields mechanism. Broadly as existing drop downs but with autocomplete when more than x input options.

### Example
In street name you can only pick from names in OS open names list, maybe with add new that is
then sent for moderation. Works on land use category i.e. Type in Industrial get prompted for
Industrial - Factory? For locations examples you'd want to combine with a bounding box so you only get back the results relevant to the tiles you can see on screen. 

@tomalrussell Have you developed this bounding box type function already? Does it limit to the tile the edit is happening in? Below is an example that works with `jQuery` which makes sense for things like landuse if the size of the array (~50kb) is acceptable. Can I also clarify that when we discussed adding street names this would be to the `search_locations` table. The source for this would be [OS Open Names](https://www.ordnancesurvey.co.uk/business-and-government/help-and-support/products/os-open-names.html) with [OS Open roads  ](https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-roads.html) 

### How it works
See demo example with landuse here: http://jsfiddle.net/dominijk/3pj8L5vh/9/.
See colouring-cities/colouring-core#358 for issue with length of enumerated types (max 63), can we split field on send request i.e. `"Building  converted to more than one dwelling - Dwellings"` too long but only need to capture `Building  converted to more than one dwelling`

List of possible entries stored in `variable` as example or `db` for roads, then made accessible to UI. 

### What else needs to be done
Collate lists of names, integrate with moderation mechanism (post oct?). Confirm which fields this runs on. 

### Db work

**Comment by polly64** [comment]
@matkoniecz for you to look at

**Comment by matkoniecz** [comment]
Yeah, if we will ned this then it can be reopened. I do not remember field which would really need it.
